config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  

  get "static_pages/home"

  get "static_pages/help"

  get "council_histories/create"

  get "council_history/create"

  resources :councils


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :properties do
    resources :build, controller: 'properties/build' 
  end  

  resources :user_steps

  resources :energy_suppliers
  resources :water_suppliers

  match '/addproperty', to: 'properties#new'
  match '/signup', to: 'users#new'
  match 'properties/:id/build', to: 'properties/build#show', :as => :building
  match '/properties/:property_id/build/:id/edit', :as => :edit_building

end

app/models/council.rb
class Council < ActiveRecord::Base
  attr_accessible :CouncilEmail, :name, :CouncilTel, :council_histories_attributes


  has_many 	 :council_histories


  has_many   :property, :through => :council_histories, :foreign_key => :property_id
end

app/controllers/councils_controller.rb
class CouncilsController < ApplicationController
  # GET /councils
  # GET /councils.json
  def index
    @councils = Council.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @councils }
    end
  end

  # GET /councils/1
  # GET /councils/1.json
  def show
    @council = Council.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @council }
    end
  end

  # GET /councils/new
  # GET /councils/new.json
  def new
    @council = Council.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @council }
    end
  end

  # GET /councils/1/edit
  def edit
    @council = Council.find(params[:id])
  end

  # POST /councils
  # POST /councils.json
  def create
    @council = Council.new(params[:council])

    respond_to do |format|
      if @council.save
        format.html { redirect_to @council, notice: 'Council was successfully created.' }
        format.json { render json: @council, status: :created, location: @council }
      else
        format.html { render action: "new" }
        format.json { render json: @council.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /councils/1
  # PUT /councils/1.json
  def update
    @council = Council.find(params[:id])

    respond_to do |format|
      if @council.update_attributes(params[:council])
        format.html { redirect_to @council, notice: 'Council was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @council.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /councils/1
  # DELETE /councils/1.json
  def destroy
    @council = Council.find(params[:id])
    @council.destroy

    respond_to do |format|
      format.html { redirect_to councils_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/councils_helper.rb
module CouncilsHelper
end

app/views/councils/_form.html.erb
<%= simple_form_for(@council) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :CouncilTel %>
    <%= f.input :CouncilEmail %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/councils/edit.html.erb
<h1>Editing council</h1>

<%= render 'form' %>

<%= link_to 'Show', @council %> |
<%= link_to 'Back', councils_path %>

app/views/councils/index.html.erb
<h1>Listing councils</h1>

<table>
  <tr>
    <th>Councilname</th>
    <th>Counciltel</th>
    <th>Councilemail</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @councils.each do |council| %>
  <tr>
    <td><%= council.CouncilName %></td>
    <td><%= council.CouncilTel %></td>
    <td><%= council.CouncilEmail %></td>
    <td><%= link_to 'Show', council %></td>
    <td><%= link_to 'Edit', edit_council_path(council) %></td>
    <td><%= link_to 'Destroy', council, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Council', new_council_path %>

app/views/councils/new.html.erb
<h1>New council</h1>

<%= render 'form' %>

<%= link_to 'Back', councils_path %>

app/views/councils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Councilname:</b>
  <%= @council.name %>
</p>

<p>
  <b>Counciltel:</b>
  <%= @council.CouncilTel %>
</p>

<p>
  <b>Councilemail:</b>
  <%= @council.CouncilEmail %>
</p>


<%= link_to 'Edit', edit_council_path(@council) %> |
<%= link_to 'Back', councils_path %>