config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  

  get "static_pages/home"

  get "static_pages/help"

  get "council_histories/create"

  get "council_history/create"

  resources :councils


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :properties do
    resources :build, controller: 'properties/build' 
  end  

  resources :user_steps

  resources :energy_suppliers
  resources :water_suppliers

  match '/addproperty', to: 'properties#new'
  match '/signup', to: 'users#new'
  match 'properties/:id/build', to: 'properties/build#show', :as => :building
  match '/properties/:property_id/build/:id/edit', :as => :edit_building

end

app/models/Property_Completion.rb
class PropertyCompletion
  attr_accessor :property, :tenants, :councils, :council_id

  def initialize(property, tenants, councils, council_histories_attributes)
    @property = property
    @councils = councils
    @tenants = tenants
  end

  def create
      if  property = Property.create(params[:councils])
      self.property_completion_notification
    end
  end

  def property_completion_notification
    PropertyMailer.welcome_email(self.property, tenants, councils).deliver
  end  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base

  attr_accessible  :city, :county, :postcode, :street1, :street2

  belongs_to :addressable, polymorphic: true

  validates_presence_of :street1, :street2, :city, :postcode, :county

  validates_uniqueness_of :postcode
end

app/models/council.rb
class Council < ActiveRecord::Base
  attr_accessible :CouncilEmail, :name, :CouncilTel, :council_histories_attributes


  has_many 	 :council_histories


  has_many   :property, :through => :council_histories, :foreign_key => :property_id
end

app/models/council_history.rb
class CouncilHistory < ActiveRecord::Base
  attr_accessible :council_id, :property_id, :vacant, :councils

  belongs_to :council

  belongs_to :property

  belongs_to :tenants


  #after_save :send_email

  private


    def send_email
    	PropertyMailer.welcome_email(property, tenants, councils).deliver
  	end

end

app/models/councils_properties.rb
class CouncilsProperties < ActiveRecord::Base
  attr_accessible :council_id, :property_id

  belongs_to :council

  belongs_to :property
end

app/models/meter.rb
class Meter < ActiveRecord::Base
  attr_accessible :EnergyDate, :EnergyMeter, :EnergyReading, :WaterDate, :WaterMeter, :WaterReading

  belongs_to :property
end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible  :name, :address_attributes, :tenants_attributes,
   :meter_attributes, :council_histories_attributes, :council,
   :property_id, :council_id, :status, :council_history_id

  belongs_to :user

  after_commit :send_email

  has_many :council_histories
  accepts_nested_attributes_for :council_histories


  has_many :councils, through: :council_histories, :foreign_key => :council_id
  accepts_nested_attributes_for :councils


  has_many :tenants, :inverse_of => :property
  accepts_nested_attributes_for :tenants, :allow_destroy => true 

  has_one :meter
  accepts_nested_attributes_for :meter, :allow_destroy => true   

  has_one :address, :as => :addressable
  accepts_nested_attributes_for :address, :allow_destroy => true



  validates :name,      :presence => :true
  validates :address,   :presence => :true
  validates :tenants,   :presence => true, :if => :active_or_tenants?
  #validates :councils,  :presence => true, :if => :send_email?


  def active?
    status == 'active'
  end

  def active_or_tenants?
    (status || '').include?('tenants') || active?
  end

  def active_or_council?
    (status || '').include?('council') || active?

  end

  def send_email
      PropertyMailer.welcome_email(self, tenants, councils).deliver
  end

 
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  attr_accessible  :property_id, :contact_type, :dateofbirth, :email, :firstname, :surname, 
  					:telno, :title

  belongs_to :property, :inverse_of => :tenants


  validates_presence_of :contact_type, :dateofbirth, :email, :surname, 
  						:firstname, :surname, :telno, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model

 

  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :properties, dependent: :destroy

  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Property.where("user_id = ?", id)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/councils_helper.rb
module CouncilsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Property App", root_path, :class => 'brand' %>

<ul class="nav pull-right">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
    
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Property App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Property App" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
               <small>
                  <a href="http://railstutorial.org/">Property App</a>
                  by Abdishakur Mohamed
                </small>
                <nav>
                  <ul>
                    <li><%= link_to "About",   '#' %></li>
                    <li><%= link_to "Contact", '#' %></li>
                    <li><a href="http://news.railstutorial.org/">News</a></li>
                  </ul>
                </nav>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/shared/_address.html.erb
<fieldset>
  
<%= f.label :street1, 'Address 1' %><br />
<%= f.text_field :street1 %>

<p>
  <%= f.label :street2, 'Address 2' %><br />
  <%= f.text_field :street2 %>
</p>
 
<p>
  <%= f.label :city %><br />
  <%= f.text_field :city %>
</p>
 
<p>
  <%= f.label :county %><br />
  <%= f.text_field :county %>
</p>
 
<p>
  <%= f.label :postcode, 'postcode' %><br />
  <%= f.text_field :postcode %>
</p>



</fieldset>
  

 

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.name %></span>

</li>

app/views/shared/_property.html.erb
<span>

	<ol>

	<tbody>

		<tr>
	  		<td><%= property.name %></td>  
	 		<td><%= property.address.try(:street1) unless property.address.street1.blank? %></td> 
	 		<td><%= property.address.try(:postcode) unless property.address.postcode.blank? %></td> 
	 		<td><%= property.tenants.first.title if property.tenants.exists? %></td> 
	 		<td><%= property.tenants.first.firstname if property.tenants.exists? %></td> 
	 		<td><%= property.tenants.first.surname if property.tenants.exists? %></td>

	 		<td><%= link_to 'Edit', edit_property_path(property) %></td>
	 		<td> <%= link_to "Delete", property, method: :delete,
                                  data: { confirm: "You sure?" } %></td>
		 </tr> 

	</tbody>	


	</ol>


	</span>

app/views/shared/_property_form.html.erb
<h1>Add New Property</h1>


<%= simple_form_for @property do |f| %>
	<%= f.error_notification %>
	<%= f.input :name %>
	<%= f.input :address %>
	<%= f.submit "Add property" %>
<% end %>

app/views/shared/_suppliers.html.erb
<fieldset>
  
<%= f.input :EnergySupplier %>
<%= f.input :EnergyTel %>
<%= f.input :EnergyEmail %>
<%= f.input :WaterSupplier %>
<%= f.input :WaterTel %>
<%= f.input :WaterEmail %>
<%= f.input :CouncilName %>
<%= f.input :CouncilTel %>
<%= f.input :CouncilEmail%>

</fieldset>
  

app/views/shared/_tenant_form.html.erb
<fieldset>
  
<%= f.input :title %>
<%= f.input :firstname %>
<%= f.input :surname %>
<%= f.input :dateofbirth %>
<%= f.input :telno %>
<%= f.input :contact_type %>
<%= f.input :emails %>

</fieldset

app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.name %>
</h1>

<span>
  <%= link_to "view my profile", current_user %>

</span>
<span>
  <%= pluralize(current_user.properties.count, "property") %>
</span>